/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const WatchMovieMovieIdLazyImport = createFileRoute('/watch/movie/$movieId')()
const watchMovieMovieIdLazyImport = createFileRoute('/(watch)/movie/$movieId')()
const WatchSerieSerieIdSeasonIndexLazyImport = createFileRoute(
  '/watch/serie/$serieId/$season/',
)()
const WatchSerieSerieIdSeasonEpisodeLazyImport = createFileRoute(
  '/watch/serie/$serieId/$season/$episode',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WatchMovieMovieIdLazyRoute = WatchMovieMovieIdLazyImport.update({
  id: '/watch/movie/$movieId',
  path: '/watch/movie/$movieId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/watch/movie/$movieId.lazy').then((d) => d.Route),
)

const watchMovieMovieIdLazyRoute = watchMovieMovieIdLazyImport
  .update({
    id: '/(watch)/movie/$movieId',
    path: '/movie/$movieId',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(watch)/movie/$movieId.lazy').then((d) => d.Route),
  )

const WatchSerieSerieIdSeasonIndexLazyRoute =
  WatchSerieSerieIdSeasonIndexLazyImport.update({
    id: '/watch/serie/$serieId/$season/',
    path: '/watch/serie/$serieId/$season/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/watch/serie/$serieId.$season.index.lazy').then(
      (d) => d.Route,
    ),
  )

const WatchSerieSerieIdSeasonEpisodeLazyRoute =
  WatchSerieSerieIdSeasonEpisodeLazyImport.update({
    id: '/watch/serie/$serieId/$season/$episode',
    path: '/watch/serie/$serieId/$season/$episode',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/watch/serie/$serieId.$season.$episode.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(watch)/movie/$movieId': {
      id: '/(watch)/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof watchMovieMovieIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/watch/movie/$movieId': {
      id: '/watch/movie/$movieId'
      path: '/watch/movie/$movieId'
      fullPath: '/watch/movie/$movieId'
      preLoaderRoute: typeof WatchMovieMovieIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/watch/serie/$serieId/$season/$episode': {
      id: '/watch/serie/$serieId/$season/$episode'
      path: '/watch/serie/$serieId/$season/$episode'
      fullPath: '/watch/serie/$serieId/$season/$episode'
      preLoaderRoute: typeof WatchSerieSerieIdSeasonEpisodeLazyImport
      parentRoute: typeof rootRoute
    }
    '/watch/serie/$serieId/$season/': {
      id: '/watch/serie/$serieId/$season/'
      path: '/watch/serie/$serieId/$season'
      fullPath: '/watch/serie/$serieId/$season'
      preLoaderRoute: typeof WatchSerieSerieIdSeasonIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/movie/$movieId': typeof watchMovieMovieIdLazyRoute
  '/watch/movie/$movieId': typeof WatchMovieMovieIdLazyRoute
  '/watch/serie/$serieId/$season/$episode': typeof WatchSerieSerieIdSeasonEpisodeLazyRoute
  '/watch/serie/$serieId/$season': typeof WatchSerieSerieIdSeasonIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/movie/$movieId': typeof watchMovieMovieIdLazyRoute
  '/watch/movie/$movieId': typeof WatchMovieMovieIdLazyRoute
  '/watch/serie/$serieId/$season/$episode': typeof WatchSerieSerieIdSeasonEpisodeLazyRoute
  '/watch/serie/$serieId/$season': typeof WatchSerieSerieIdSeasonIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/(watch)/movie/$movieId': typeof watchMovieMovieIdLazyRoute
  '/watch/movie/$movieId': typeof WatchMovieMovieIdLazyRoute
  '/watch/serie/$serieId/$season/$episode': typeof WatchSerieSerieIdSeasonEpisodeLazyRoute
  '/watch/serie/$serieId/$season/': typeof WatchSerieSerieIdSeasonIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie/$movieId'
    | '/watch/movie/$movieId'
    | '/watch/serie/$serieId/$season/$episode'
    | '/watch/serie/$serieId/$season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie/$movieId'
    | '/watch/movie/$movieId'
    | '/watch/serie/$serieId/$season/$episode'
    | '/watch/serie/$serieId/$season'
  id:
    | '__root__'
    | '/'
    | '/(watch)/movie/$movieId'
    | '/watch/movie/$movieId'
    | '/watch/serie/$serieId/$season/$episode'
    | '/watch/serie/$serieId/$season/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  watchMovieMovieIdLazyRoute: typeof watchMovieMovieIdLazyRoute
  WatchMovieMovieIdLazyRoute: typeof WatchMovieMovieIdLazyRoute
  WatchSerieSerieIdSeasonEpisodeLazyRoute: typeof WatchSerieSerieIdSeasonEpisodeLazyRoute
  WatchSerieSerieIdSeasonIndexLazyRoute: typeof WatchSerieSerieIdSeasonIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  watchMovieMovieIdLazyRoute: watchMovieMovieIdLazyRoute,
  WatchMovieMovieIdLazyRoute: WatchMovieMovieIdLazyRoute,
  WatchSerieSerieIdSeasonEpisodeLazyRoute:
    WatchSerieSerieIdSeasonEpisodeLazyRoute,
  WatchSerieSerieIdSeasonIndexLazyRoute: WatchSerieSerieIdSeasonIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(watch)/movie/$movieId",
        "/watch/movie/$movieId",
        "/watch/serie/$serieId/$season/$episode",
        "/watch/serie/$serieId/$season/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/(watch)/movie/$movieId": {
      "filePath": "(watch)/movie/$movieId.lazy.tsx"
    },
    "/watch/movie/$movieId": {
      "filePath": "watch/movie/$movieId.lazy.tsx"
    },
    "/watch/serie/$serieId/$season/$episode": {
      "filePath": "watch/serie/$serieId.$season.$episode.lazy.tsx"
    },
    "/watch/serie/$serieId/$season/": {
      "filePath": "watch/serie/$serieId.$season.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
